### ISSUE TITLE
Extra invite-row created on refresh

### ISSUE THREAD

**Issue by yankwong** [amcnulty/Whoop-It-Up#60]
Steps to replicate it:

1) go to http://localhost:8080/profile/getUser/1
2) make sure there is an event invite for this user
3) signin
4) go to the Invite tab and notice there are now two rows
5) refresh
6) go to the Invite tab and notice there are now 3 rows

**Comment by amcnulty** [comment]
This has been fixed. On the server all of the events were being pushed to an array that never got emptied.
